spring:
  liquibase:
    change-log: classpath:config/liquibase/invoice-master.xml
    default-schema: INVOICE
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
    url: jdbc:h2:tcp://localhost:1521/default;INIT=CREATE SCHEMA IF NOT EXISTS INVOICE
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    type: com.zaxxer.hikari.HikariDataSource
  h2:
    console:
      enabled: false
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Toronto
    hibernate:
      ddl-auto: none
    show-sql: false
