spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
    url: jdbc:h2:file:../invoice-db/invoiceDB;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    platform: h2
    username: sa
    type: com.zaxxer.hikari.HikariDataSource
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false