spring:
  liquibase:
    change-log: classpath:config/liquibase/invoice-master.xml
    default-schema: INVOICE
  datasource:
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      minimum-idle: 1
      maximum-pool-size: 5
    url: jdbc:p6spy:h2:tcp://localhost:1521/default;INIT=CREATE SCHEMA IF NOT EXISTS INVOICE
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    platform: h2
    username: sa
    type: com.zaxxer.hikari.HikariDataSource
    continue-on-error: true
  h2:
    console:
      enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          time_zone: America/Toronto
    hibernate:
      ddl-auto: none
    show-sql: false
