spring:
  liquibase:
    change-log: classpath:config/liquibase/invoice-master.xml
  datasource:
    hikari:
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
    type: com.zaxxer.hikari.HikariDataSource
    continue-on-error: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Toronto
    hibernate:
      ddl-auto: none
    show-sql: false
jasypt:
  encryptor:
    algorithm: PBEWITHHMACSHA256ANDAES_256
    password: ${JASYPT_PWD}

---
spring:
  profiles: dev
  liquibase:
    default-schema: invoice
  datasource:
    url: jdbc:p6spy:h2:tcp://localhost:1521/default
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    platform: h2
    username: sa
  h2:
    console:
      enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

---
spring:
  profiles: prod
  liquibase:
    default-schema: invoice
  datasource:
    url: ${INVOICE_DB_LOCATION}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: ${PROD_PWD}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

