 hibernate:
   c3p0:
     max_size: 10
     initial_pool_size: 10
 spring:
  datasource:
    url: jdbc:h2:file:./invoice-db/invoiceDB;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    platform: h2
    initialize: false
    username: sa
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false


