server:
  port: 8080
jsf:
  project-stage: Development
  facelets-skip-comments: true
  interpret-empty-string-submitted-values-as-null: true
  datetimeconverter-default-timezone-is-system-timezone: true
  state-saving-method: server
  default-suffix: .xhtml
spring:
  profiles:
    include: database
endpoints:
  shutdown:
    enabled: true