INSERT INTO INVOICE.TAX (PERCENT, IDENTIFIER) VALUES (0.13, 'HST');
INSERT INTO INVOICE.TAX (PERCENT, IDENTIFIER) VALUES (0.0, 'No Tax');

INSERT INTO INVOICE.CURRENCY (NAME, DESCRIPTION) VALUES ('CAD', 'Canadian Dollar');
INSERT INTO INVOICE.CURRENCY (NAME, DESCRIPTION) VALUES ('USD', 'USA Dollar');

INSERT INTO INVOICE.ROLES (ROLE_ID, ROLE_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO INVOICE.ROLES (ROLE_ID, ROLE_NAME) VALUES (2, 'ROLE_USER');

INSERT INTO INVOICE.USERS (USER_ID, USERNAME, PASSWORD, LAST_LOGGED, ENABLED)
VALUES (1, 'john', '$2a$10$2VfGSFh/GPiQ44TiENuYgO7A7jz7C6Kog6Gg3sB07cQfW884nP52O', NULL, TRUE);

INSERT INTO INVOICE.CONTACTS (FIRST_NAME, LAST_NAME, MIDDLE_NAME, EMAIL, ADDRESS_LINE1, ADDRESS_LINE2, PHONE1, USER_ID)
VALUES ('John', 'Smith', NULL, 'john@john.com', 'Address1', 'Address2', '905-234-2345', 1);

INSERT INTO INVOICE.USER_ROLE (USER_ID, ROLE_ID, DATE_ASSIGNED) VALUES (1, 1, SYSTIMESTAMP);

INSERT INTO INVOICE.COMPANIES (COMPANY_NAME, SHORT_NAME, ADDRESS_LINE1, ADDRESS_LINE2, PHONE1, OWNED_BY_ME, BUSINESS_NUMBER, CONTENT)
VALUES ('Test name', 'TN', 'Address1', 'Address2', '905-234-2344', TRUE, 'BNF0012301230213', NULL);

INSERT INTO INVOICE.OAUTH_CLIENT_DETAILS (CLIENT_ID, RESOURCE_IDS, CLIENT_SECRET, SCOPE, AUTHORIZED_GRANT_TYPES, WEB_SERVER_REDIRECT_URI, AUTHORITIES, ACCESS_TOKEN_VALIDITY, REFRESH_TOKEN_VALIDITY, ADDITIONAL_INFORMATION, AUTOAPPROVE)
VALUES ('my-client-1', '76dc37bb-ab66-4971-a528-5ac5fd5e2eb0', '', 'profile', 'authorization_code', null, 'ROLE_CLIENT', 3600, null, '{}', 'true');

COMMIT;