branch-defaults:
  feature/bc/api:
    environment: MyOpenInvoice-env
environment-defaults:
  MyOpenInvoice-env:
    branch: null
    repository: null
global:
  application_name: My Open Invoice
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Java 8 running on
    64bit Amazon Linux/2.8.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
