server:
  port: 8080
  context-path: /api
spring:
  profiles:
    include: database
endpoints:
  shutdown:
    enabled: true
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
