management:
  endpoint:
    shutdown:
      enabled: true
spring:
  liquibase:
    enabled: false
  profiles:
    include: database
    active: database
  application:
    name: my-open-invoice
jasypt:
  encryptor:
    password: mypassword
    algorithm: PBEWITHMD5ANDDES