server:
  port: 8080
  context-path: /api
spring:
  thymeleaf:
    cache: true
    suffix: .xhtml
  profiles:
    include: database
endpoints:
  shutdown:
    enabled: true
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
security:
  basic:
    enabled: false