management:
  endpoint:
    shutdown:
      enabled: true
spring:
  liquibase:
    enabled: false
  profiles:
    include: database
    active: database
  application:
    name: my-open-invoice
  jackson:
    time-zone: America/Toronto
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
jasypt:
  encryptor:
    password: mypassword
    algorithm: PBEWITHMD5ANDDES