management:
  endpoint:
    shutdown:
      enabled: true
spring:
  liquibase:
    enabled: false
  profiles:
    include: database
    active: database
  application:
    name: my-open-invoice
  jackson:
    time-zone: America/Toronto
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
jasypt:
  encryptor:
    password: mypassword
    algorithm: PBEWITHMD5ANDDES
app:
  jwtSecret: secret
  jwtExpirationInMs: 604800000