CREATE TABLE INVOICE.OAUTH_ACCESS_TOKEN (
  TOKEN_ID          VARCHAR(256) DEFAULT NULL,
  TOKEN             BLOB,
  AUTHENTICATION_ID VARCHAR(256) DEFAULT NULL,
  USER_NAME         VARCHAR(256) DEFAULT NULL,
  CLIENT_ID         VARCHAR(256) DEFAULT NULL,
  AUTHENTICATION    BLOB,
  REFRESH_TOKEN     VARCHAR(256) DEFAULT NULL
);

CREATE TABLE INVOICE.OAUTH_REFRESH_TOKEN (
  TOKEN_ID       VARCHAR(256) DEFAULT NULL,
  TOKEN          BLOB,
  AUTHENTICATION BLOB
);