INSERT INTO INVOICE.TAX (PERCENT, IDENTIFIER) VALUES (0.13, 'HST');
INSERT INTO INVOICE.TAX (PERCENT, IDENTIFIER) VALUES (0.0, 'No Tax');

INSERT INTO INVOICE.CURRENCY (NAME, DESCRIPTION) VALUES ('CAD', 'Canadian Dollar');
INSERT INTO INVOICE.CURRENCY (NAME, DESCRIPTION) VALUES ('USD', 'USA Dollar');

INSERT INTO INVOICE.ROLES (ROLE_ID, ROLE_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO INVOICE.ROLES (ROLE_ID, ROLE_NAME) VALUES (2, 'ROLE_USER');

INSERT INTO INVOICE.USERS (USER_ID, USERNAME, PASSWORD, LAST_LOGGED, ENABLED)
VALUES (1, 'bcavlin', '$2a$10$2VfGSFh/GPiQ44TiENuYgO7A7jz7C6Kog6Gg3sB07cQfW884nP52O', NULL, TRUE);
INSERT INTO INVOICE.USERS (USER_ID, USERNAME, PASSWORD, LAST_LOGGED, ENABLED)
VALUES (2, 'jane', '$2a$10$2VfGSFh/GPiQ44TiENuYgO7A7jz7C6Kog6Gg3sB07cQfW884nP52O', NULL, TRUE);

INSERT INTO INVOICE.CONTACTS (FIRST_NAME, LAST_NAME, MIDDLE_NAME, EMAIL, ADDRESS_LINE1, ADDRESS_LINE2, PHONE1, USER_ID)
VALUES ('John', 'Smith', NULL, 'bcavlin@hotmail.com', 'Address1', 'Address2', '905-234-2345', 1);

INSERT INTO INVOICE.USER_ROLE (USER_ID, ROLE_ID, DATE_ASSIGNED) VALUES (1, 1, SYSTIMESTAMP);

INSERT INTO INVOICE.COMPANIES (COMPANY_NAME, SHORT_NAME, ADDRESS_LINE1, ADDRESS_LINE2, PHONE1, OWNED_BY_ME, BUSINESS_NUMBER, CONTENT)
VALUES ('Test name', 'TN', 'Address1', 'Address2', '905-234-2344', TRUE, 'BNF0012301230213', NULL);

COMMIT;